### ISSUE TITLE
receive error after clone - TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by shawndwells** [jenglish/ssptool#2]
$ node /var/www/html/ssptool/main.js server
Loading data...
Initializing...
`````/var/www/html/ssptool/lib/routes.js:188
    pgq[''].forEach(addPage);
           ^

TypeError: Cannot read property 'forEach' of undefined
    at addPages (/var/www/html/ssptool/lib/routes.js:188:12)
    at Object.buildSite (/var/www/html/ssptool/lib/routes.js:289:5)
    at EventEmitter.app.initialize (/var/www/html/ssptool/app.js:66:12)
    at startServer (/var/www/html/ssptool/main.js:63:15)
    at opencontrol.load (/var/www/html/ssptool/main.js:72:31)
    at async.series (/var/www/html/ssptool/lib/opencontrol/index.js:34:22)
    at /var/www/html/ssptool/node_modules/async/dist/async.js:3861:9
    at /var/www/html/ssptool/node_modules/async/dist/async.js:421:16
    at replenish (/var/www/html/ssptool/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/var/www/html/ssptool/node_modules/async/dist/async.js:931:17)`````

**Comment by jenglish** [comment]
Ah! Sorry, dumb mistake on my part.  This will happen if there are no markdown pages. Fix on the way.

**Comment by shawndwells** [comment]
FYI. Used ssptool to visualize changes made to OpenControl content live during OpenStack Sydney:

https://www.openstack.org/summit/sydney-2017/summit-schedule/events/20012/openstack-compliance-speed-and-agility-yes-its-possible

Super helpful tool! Great work.
